[module]
  [[module.imports]]
    path = "github.com/disic/frago"

title = "Commando UX"
theme = ["frago"]

[params]
  logo = "Commando UX <small>Défi de mise en conformité de démarches en ligne</small>"

