name = "Documantago"
license = "MIT"
licenselink = "https://github.com/zerostatic/hugo-whisper-theme/blob/master/LICENSE"
description = "Documantago is a minimal documentation theme built for Hugo. The design and functionality is intentionally minimal."

homepage = "https://github.com/bertrandkeller/documentago"

tags = ["docs","responsive","minimal","clean","bootstrap","zerostatic"]
features = ["docs","bootstrap","scss","netlify","google analytics"]

theme_version = "1.0.0"

[author]
  name = "Robert Austin"
  homepage = "https://www.zerostatic.io"
